server.port=8084

spring.application.name=notification-service

# RabbitMQ Configuration
spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://bjfpsicq:GvGmz_AjSvl09SaX_rTJcA0AXe_egtoy@fuji.lmq.cloudamqp.com/bjfpsicq}
